### ISSUE TITLE
Description typo

### ISSUE THREAD

**Issue by mokagio** [lzwjava/Reveal-In-GitHub#1]
Hi, nice plugin 😊

There is a typo in the description, `shorcut` instead for `shortcut`.

Also, it is spelled GitHub, not Github. 

Keepup the good work :+1:

**Comment by lzwjava** [comment]
Well, fixed it by https://github.com/lzwjava/Reveal-In-GitHub/commit/35786bddbb18667e2d2c67fabc856a05225102ec

Now Github never show up in code or README.

Poor me, being wrong for so many years. I never thought about that before. Thanks you for pointing out. It's GitHub!

**Comment by mokagio** [comment]
No worries :smile:
