### ISSUE TITLE
Installation through Alcatraz fails

### ISSUE THREAD

**Issue by shawnmorrison** [lzwjava/Reveal-In-GitHub#4]
When installing through Alcatraz the installation starts then stops. The console reports:

`11/24/15 7:57:23.606 AM Xcode[10854]: Updating Repo: /**************/Library/Application Support/Alcatraz/Plug-ins/Reveal-In-Github
11/24/15 7:57:24.691 AM Xcode[10854]: Wasn't able to find: Reveal-In-Github.xcodeproj in /**************/Library/Application Support/Alcatraz/Plug-ins/Reveal-In-Github`

This is because the actual project name is 'Reveal-In-GitHub.xcodeproj' (note the capital H). I was able to rename the project to complete installation.

**Comment by lzwjava** [comment]
thanks，I will fix it right now.

**Comment by lzwjava** [comment]
It should be fixed. See https://github.com/alcatraz/alcatraz-packages/issues/418
